# Generated by Django 5.0.6 on 2024-05-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('create_chat', 'Create chat'), ('add_users_to_chat', 'Add users to chat'), ('remove_users_from_chat', 'Remove users from chat')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('edit_own_message', 'Edit own message'), ('delete_own_message', 'Delete own message')]},
        ),
    ]
