# Generated by Django 5.0.6 on 2024-05-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_chat_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('create_chat', 'Can Create chat'), ('add_users_to_chat', 'Can Add users to chat'), ('remove_users_from_chat', 'Can Remove users from chat')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('edit_own_message', 'Can Edit own message'), ('delete_own_message', 'Can Delete own message')]},
        ),
    ]
