# Generated by Django 5.0.6 on 2024-06-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_messagelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='cation',
            new_name='action',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messenger.message'),
            preserve_default=False,
        ),
    ]
