version: '3'

services:
  django_app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./hillel_messenger:/django_app/hillel_messenger
    ports:
      - "8000:8000"
    depends_on:
      - psql_db

  psql_db:
    image: postgres
    environment:
      POSTGRES_DB: django_db2
      POSTGRES_USER: user_django_db2
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celety-beat:
    build: .
    command: celery -A hillel_messenger beat -l info
    volumes:
      - ./hillel_messenger:/django_app/hillel_messenger
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-worker:
    build: .
    command: celery -A hillel_messenger worker -l info
    volumes:
      - ./hillel_messenger:/django_app/hillel_messenger
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0